create table person
(
    id         int generated by default as identity primary key,
    full_name  varchar(100) not null unique,
    birth_year int          not null
);

create table book
(
    id               int generated by default as identity primary key,
    title            varchar(100) not null,
    author           varchar(100),
    publication_year int,
    person_id        int          references person (id) on delete set null
);